<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardRepository extends EntityRepository
{
    public function findInFestival($feast_id)
    {
        $q = $this->getEntityManager()->createQuery(
            "SELECT a FROM BackendBundle:Award a
			WHERE a.feast = $feast_id
			ORDER BY a.id ASC"
        );
        return $q->getResult();
    }

} // end class