<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeastStageRepository extends EntityRepository
{
    public function findInFestival($feast_id)
    {
        $q = $this->getEntityManager()->createQuery(
            "SELECT fs FROM BackendBundle:FeastStage fs
			WHERE fs.feast = $feast_id
			ORDER BY fs.id ASC"
        );
        return $q->getResult();
    }
    //
    public function setFiltroByUser($authorization, $storage)
    {
        if ($authorization->isGranted('ROLE_SUPER_ADMIN'))
        {
            $filtro = 'fs.feast > 0';
        } else {
            $token  = $storage->getToken();
            $user   = $token->getUser();
            $filtro = 'fs.feast = '.$user->getFeast()->getId();
        }
        return $filtro;
    }

} // end class