<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationScheduleRepository extends EntityRepository
{
    public function findForProcess()
    {
        $q = $this->getEntityManager()->createQuery
        (
            "SELECT ns FROM BackendBundle:NotificationSchedule ns WHERE ns.status = 0 ORDER BY ns.notificationId ASC"
        );
        $q->setFirstResult(0);
        $q->setMaxResults(25);
        return $q->getResult();
    }
}
