<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function findInFestival($feast_id)
    {
        $q = $this->getEntityManager()->createQuery(
            "SELECT n FROM BackendBundle:Notification n
			WHERE n.feast = $feast_id
			ORDER BY n.id ASC"
        );
        return $q->getResult();
    }

} // end class