<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Proxies\__CG__\CoolwayFestivales\BackendBundle\Entity\FeastStage;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends EntityRepository
{
    public function findInFestival($feast_id)
    {
        $q = $this->getEntityManager()->createQuery(
            "SELECT s FROM BackendBundle:Stage s
            LEFT JOIN BackendBundle:FeastStage fs WITH fs.stage = s.id
			WHERE fs.feast = $feast_id
			ORDER BY s.id ASC"
        );
        return $q->getResult();
    }
    //
    public function addStageToFestival($stage_id, $festival_id)
    {
        $em = $this->getEntityManager();
        $stage = $em->getRepository('BackendBundle:Stage')->find($stage_id);
        $feast = $em->getRepository('BackendBundle:Feast')->find($festival_id);

        if ($stage && $feast)
        {
            $obj = new FeastStage();
            $obj->setFeast($feast);
            $obj->setStage($stage);

            $em->persist($obj);
            $em->flush();
        }
    }
    //
    public function delStageFromFestival($stage_id, $festival_id)
    {
        $em = $this->getEntityManager();
        $entity = $em->getRepository('BackendBundle:FeastStage')->findOneBy(array('feast' => $festival_id, 'stage'=>$stage_id));

        if ($entity)
        {
            $em->remove($entity);
            $em->flush();
        }
    }

} // end class