<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends EntityRepository
{
	public function findSlider($feast_id)
	{
		$q = $this->getEntityManager()->createQuery(
			"SELECT s FROM BackendBundle:Step s
			WHERE s.feast = $feast_id 
			ORDER BY s.steps ASC"
		);
		
		return $q->getResult();
	}
	//
	public function setFiltroByUser($authorization, $storage)
	{
		if ($authorization->isGranted('ROLE_SUPER_ADMIN'))
		{
			$filtro = 'f.id > 0';
		} else {
			$token  = $storage->getToken();
			$user   = $token->getUser();
			$filtro = 'f.id = '.$user->getFeast()->getId();
		}
		return $filtro;
	}

} // end class