<?php

namespace CoolwayFestivales\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermsRepository extends EntityRepository
{
    public function findInFestival($feast_id)
    {
        $q = $this->getEntityManager()->createQuery(
            "SELECT t FROM BackendBundle:Terms a
			WHERE t.feast = $feast_id
			ORDER BY t.id ASC"
        );
        return $q->getResult();
    }

} // end class