safety:
    resource: "@SafetyBundle/Controller/"
    type:     annotation
    prefix:   /admin

frontend:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /
