security:
    acl:
        connection: default

    encoders:
        CoolwayFestivales\SafetyBundle\Entity\User: {algorithm: sha512, encode_as_base64: true, iterations: 10}

    providers:
        usuarios:
            entity: { class: CoolwayFestivales\SafetyBundle\Entity\User, property: username }
        chain_provider:
            chain:
                providers: [usuarios]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:      ^/api
            stateless:    true
            anonymous:    true

        weather_crone:
            pattern:      ^/admin/weather/update
            stateless:    true
            anonymous:    true

        notification_crone:
            pattern:      ^/admin/notification/send/all
            stateless:    true
            anonymous:    true

        notification_schedule_crone:
            pattern:      ^/admin/notification-schedule/send/scheduled
            stateless:    true
            anonymous:    true

        notification_schedule_crone2:
                    pattern:      ^/admin/notification-schedule/send/scheduled2
                    stateless:    true
                    anonymous:    true

        artist_favorite_crone:
            pattern:      ^/admin/notification/send/artist-favorite/
            stateless:    true
            anonymous:    true

        backend:
            pattern: ^/admin
            form_login:
                provider: chain_provider
                login_path: /admin/login
                check_path: /admin/login_check
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
            logout:
                target: /admin/login
                path: /admin/logout
            anonymous:    true
            remember_me:
                key:        admin
                lifetime:   86400


    access_control:
        - { path: ^/admin/notification/send/test,                                  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/notification/send/all,                              roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/notification/send/artist-favorite,                  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/notification-schedule/send/scheduled,               roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/notification-schedule/send/scheduled2,              roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/weather/update,                                     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$,                                             roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,                                                   roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_COOLWAY, ROLE_USER] }
