security:
    acl:
        connection: default

    encoders:
        CoolwayFestivales\SafetyBundle\Entity\User: {algorithm: sha512, encode_as_base64: true, iterations: 10}

    #role_hierarchy:
    #    ROLE_CUSTOMER: ROLE_ALLOWED_TO_SWITCH
    #    ROLE_CMS: ROLE_ALLOWED_TO_SWITCH
    #    ROLE_USER: ROLE_ALLOWED_TO_SWITCH
    #    ROLE_ADMIN: [ROLE_CUSTOMER, ROLE_USER, ROLE_CMS, ROLE_EMPRESA]

    providers:
        chain_provider:
            chain:
                providers: [usuarios]
        usuarios:
            entity: { class: CoolwayFestivales\SafetyBundle\Entity\User, property: username }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        login_cms:
            pattern:  ^/login$
            security: false

        # Firewall global utilizado en la parte pública o frontend
#        frontend:
#            pattern: ^/
#            provider: usuarios
#            anonymous: ~
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                use_referer: true
#                default_target_path: /dashboard
#                always_use_default_target_path: false
#            logout:
#                path: /logout
#                target: /
#            remember_me:
#                key:        cms
#                lifetime:   86400

        backend:
            pattern:        ^/admin
            provider:       usuarios
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
            logout:
                path: /admin/logout
                target: /admin/login
            remember_me:
                key:        admin
                lifetime:   86400
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN]}
