security:
    acl:
        connection: default

    encoders:
        CoolwayFestivales\SafetyBundle\Entity\User: {algorithm: sha512, encode_as_base64: true, iterations: 10}

    providers:
        chain_provider:
            chain:
                providers: [usuarios]
        usuarios:
            entity: { class: CoolwayFestivales\SafetyBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        weather_crone:
            pattern:      ^/admin/weather/update
            stateless:    true
            anonymous:    true

        notification_crone:
            pattern:      ^/admin/notification/send/all
            stateless:    true
            anonymous:    true

        login:
            pattern:  ^/admin/login$
            security: false

        login_cms:
            pattern:  ^/login$
            security: false

        backend:
            pattern:        ^/admin
            provider:       usuarios
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
            logout:
                path: /admin/logout
                target: /admin/login
            remember_me:
                key:        admin
                lifetime:   86400


#    access_control:
#        - { path: ^/admin, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_COOLWAY]}
#        - { path: ^/admin/notification/send/all, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/weather/update, role: IS_AUTHENTICATED_ANONYMOUSLY }