# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    push_notification.ionic:
        class: CoolwayFestivales\BackendBundle\Services\IonicPush
        arguments: [%ionic_token%, %ionic_profile%]