services:
    coolway_app.gcm:
        class: CoolwayFestivales\BackendBundle\Services\GCM
    coolway_app.apn:
        class: CoolwayFestivales\BackendBundle\Services\APN
        arguments:
            "container": "@service_container"
