api_user:
    type: rest
    resource: CoolwayFestivalesApiBundle:User

api_authentication:
    type: rest
    resource: CoolwayFestivalesApiBundle:Authentication

api_artist:
    type: rest
    resource: CoolwayFestivalesApiBundle:Artist

api_poster:
    type: rest
    resource: CoolwayFestivalesApiBundle:Poster

api_map:
    type: rest
    resource: CoolwayFestivalesApiBundle:Map

api_favorite:
    type: rest
    resource: CoolwayFestivalesApiBundle:Favorite

api_notification:
    type: rest
    resource: CoolwayFestivalesApiBundle:Notification

api_weather:
    type: rest
    resource: CoolwayFestivalesApiBundle:Weather

api_version:
    type: rest
    resource: CoolwayFestivalesApiBundle:Version