api_customer:
    type: rest
    resource: CoolwayFestivalesApiBundle:Customer

api_artist:
    type: rest
    resource: CoolwayFestivalesApiBundle:Artist

api_poster:
    type: rest
    resource: CoolwayFestivalesApiBundle:Poster

api_map:
    type: rest
    resource: CoolwayFestivalesApiBundle:Map